# Generated by Django 4.2.21 on 2025-08-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price_pence',
            field=models.PositiveIntegerField(default=9000),
        ),
    ]
