# Generated by Django 4.2.21 on 2025-09-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_price_pence'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='download_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
