# Generated by Django 4.2.21 on 2025-09-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_download_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='capton',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='download_path_bw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='price_pence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
