# Generated by Django 4.2.21 on 2025-09-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_photo_options_remove_photo_capton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
