# Generated by Django 4.2.21 on 2025-09-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileForm',
        ),
    ]
