# Generated by Django 4.2.21 on 2025-09-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.CharField(choices=[('colour', 'Colour'), ('bw', 'Black & White')], default='colour', max_length=10),
        ),
    ]
