# Generated by Django 4.2.21 on 2025-09-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_variant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'review', 'accepted'])), fields=('event_date',), name='unique_booking_per_day_when_active'),
        ),
    ]
