# Generated by Django 4.2.21 on 2025-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bookingrequest_unique_booking_per_day_when_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingrequest',
            name='unique_booking_per_day_when_active',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='deposit_pence',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
